### ISSUE TITLE
Agree on Sprint Cadence and Capacity

### ISSUE THREAD

**Issue by jwiggs35** [jwiggs35/jwiggs-design#2]
Discuss and agree upon a reasonable sprint cadence and capacity/availability to work on our project.

**Comment by jwiggs35** [comment]
@Jwiggs27 so if we are going to do scrum. do you want to do 1 or 2 week sprints? and do you have a rough idea of how much time you want to devote to this work?

**Comment by Jwiggs27** [comment]
I think maybe 2 week sprints and I could probably put quite a bit of time in (maybe like 10 hours or so a week.) I don't know is that to much or not enough haha?

**Comment by jwiggs35** [comment]
oh nice, yeah that seems like a solid chunk of time (I am not going to hold you to that by any means, it's just helpful when determining how much work to take on each sprint). idk if I am going to be able to commit that much early on. I was thinking like 2 hours a week or so, but that's probably for the best anyways so you can get credit for doing the majority of the work haha. I am cool with 2 week sprints. if you are cool with all of that i think you can go ahead and close this issue!
